repository:
  name: tsangertype-fonts.nix
  description: TsangerType Fonts for Nix/NixOS user.
  homepage: https://tsanger.cn/product
  topics: nix-flake, nixos-flake, fonts, chinese-fonts
  private: false

  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
