repository:
  name: chinese-fonts-overlay
  description: Chinese fonts collection for Nix/NixOS user.
  topics: chinese-fonts, fonts, nix-flake, nix-packages, nix-overlays, nixos-flake
  private: false

  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
